### PR TITLE
add Simon bio,

### PR DESCRIPTION
**Pull request by SimonLab**
add a short bio on my profile, ref: #288

### CODE REVIEW

**Comment by rub1e** [comment]
Good man @SimonLab ! I love how confident you are using foreign words mixed in with English :wink: I also am impressed how you've managed to write a bio without talking about yourself at all :grin: 

My only comment is - is it ok to have the `npm debug log` committed? If so I'll merge at once, just let me know :smile:

**Comment by rub1e** [comment]
@iteles it's all in how you ask :wink: 

If someone lets me know about the `npm debug log` then I'll merge in due course :smile:

**Comment by iteles** [comment]
@rub1e The `npm debug log` line is just Simon adding it to the `.gitignore` so that the log _doesn't_ get uploaded to github, so all good, you can go ahead and merge!

**Comment by rub1e** [comment]
OMG I'm an idiot - ignore me :disappointed:

**Comment by rub1e** [comment]
Is it obvious I've been coding solo for quite a while now...? :worried:

**Pull request merged**
