### PR TITLE
Add new Thomas Cook logo

### LINKED ISSUE #467: Update Thomas Cook logo
Update the TC logo before the TC Serverless case study can be linked to from our portfolio page:
https://dwyl.com/case-studies/thomas-cook/tc-serverless

From:
image

To:
http://www.stickpng.com/img/icons-logos-emojis/iconic-brands/thomas-cook-logo

thomas-cook-logo

### PR DESCRIPTION
**Pull request by Dana94**
Closes #467

### CODE REVIEW

**Comment by Dana94** [comment]
I did have trouble committing this before but I thought I figured it out. I'll look into it @nelsonic

**Comment by Dana94** [comment]
@iteles I'm not sure if I understand you. The issue is just asking to replace the old logo image with its new logo right?

**Comment by iteles** [comment]
@Dana94 Right! But the logo is currently being used in https://dwyl.com/case-studies/thomas-cook/tc-serverless, so if you change the name of the logo file, then you'll need to also change it in the code of that page (https://github.com/dwyl/dwyl-site/blob/master/case-studies/thomas-cook/tc-serverless.html) so that the updated logo actually appears  ☺️

**Comment by Dana94** [comment]
@iteles True, but I wouldn't need to change the file calling the image if the new logo file has the same name as the old logo file. I could do this by removing the old logo file from the repo.

This is the branch locally showing the new logo.
image

Please let me know if I'm missing something.

**Comment by iteles** [comment]
@Dana94 That's exactly right. Both my comments mentioned _if_ you change the file name ☺️

**Comment by Dana94** [comment]
@iteles Ah gotcha, okay I did _not_ change the file name. 😄

**Pull request merged**
