### PR TITLE
[WiP] Redesigned navbar and homepage

### PR DESCRIPTION
**Pull request by finnhodgkin**
**Not ready for merge**

This is just a test branch so we can see what the live site would look like with the navbar, padding and font size from the original designs.

Currently only applies to the home and portfolio pages (white navbar viewable on the portfolio page).

I think it looks a **lot** nicer than the currently live page, but there may be reasons for some of the changes that I don't know about.

### CODE REVIEW

**Comment by ZooeyMiller** [comment]
Looks way better being more true to the original design :+1: :sparkles:

**Comment by finnhodgkin** [comment]
For anyone who doesn't want to go through the hassle of pulling down and running live-server, here are some screenshots of the differences

### Home
**live:**
app website and software development training london dwyl - google chrome_080
**new version:**
app website and software development training london dwyl - google chrome_079


### Portfolio
**live:**
portfolio responsive web and mobile applications dwyl - google chrome_078

**new version:**
portfolio responsive web and mobile applications dwyl - google chrome_077

**Comment by markwilliamfirth** [comment]
@finnhodgkin screenshots look great! Personally would quite like it if the portfolio cards are square (can't tell if they are). Also teal blog link on white nav might throw an accessibility error(?). If the drop shadow is now gone from the nav, does it appear when scrolling down and when the mobile nav menu pops out? This was added to ensure the user could tell where the nav starts and ends

**Comment by finnhodgkin** [comment]
The navbar works in the same way as on invision, it just covers content with the background colour. IMO this is just as clear as a drop shadow, but looks nicer on pageload.

**Comment by finnhodgkin** [comment]
@markwilliamfirth Yeah looks like you're right about the teal. Do you think it's worth me going through the whole site making changes to move it back to the original designs? 

It's not a very small job so definitely need feedback before jumping in.

**Comment by markwilliamfirth** [comment]
I think minor design changes are probably a p3 so this one can probably wait until all the p2s are done

When we come back to this perhaps we can just make the blog link not teal when on a white background

With reference to the comment about covering / drop shadow:

These are the designs: https://github.com/dwyl/dwyl-site/issues/268#issuecomment-328611498

If this has been implemented, great, if not, then that is what they should look like

Don't want to pull down at the moment as this PR is still a WiP

**Comment by finnhodgkin** [comment]
On Invision the only menu with a drop shadow is the mobile one. We could just apply the shadow when the mobile menu is open. 

Will continue working on P2s for now anyway. :+1:

**Comment by finnhodgkin** [comment]
Closing this because #419 does a better job.

**Pull request closed without merging**
