### PR TITLE
Close overlay nav menu on contact click (uses JS)

### PR DESCRIPTION
**Pull request by finnhodgkin**
Adds a small amount of JS to close the overlay-ed nav menu when the contact link is clicked. I'm not sure where we stand with JS on the site, but I'm guessing as it doesn't break anything with JS disabled it should be fine :+1:

#369

### CODE REVIEW

**Comment by markwilliamfirth** [comment]
@finnhodgkin js policy is here: https://github.com/dwyl/dwyl-site/issues/317

**Comment by markwilliamfirth** [comment]
How do I test this? Testing locally (file:///Users/mark/GitHub/dwyl-site/index.html#contact) doesn't appear to work and 'npm install && npm run dev' from here https://github.com/dwyl/dwyl-site/blob/master/redesign_readme.md doesn't work either

**Comment by finnhodgkin** [comment]
@markwilliamfirth Thanks for the issue link :+1:

> Happy to use JavaScript to enhance the UX, but it must gracefully degrade to what you have above when JS is switched off 

Looks like exactly this use case.

I'm using life-server to automatically refresh the page. Works perfectly with that, not sure why it's not without, but I'll look into it now.

**Comment by finnhodgkin** [comment]
@markwilliamfirth Now testable locally without live-server.

**Comment by finnhodgkin** [comment]
Oh wait I just realised this still needs ids adding to other pages. Taking off awaiting review.

**Comment by markwilliamfirth** [comment]
@finnhodgkin was just about to say only works on home page

**Comment by finnhodgkin** [comment]
@markwilliamfirth Sorry, pre-lunch hunger brain. Fixed now :+1:

**Comment by markwilliamfirth** [comment]
assigning @iteles to ensure she's happy with the use of js

**Comment by markwilliamfirth** [comment]
@iteles this ok to merge?

**Comment by markwilliamfirth** [comment]
have resolved changes and merged

**Comment by iteles** [comment]
I thought we were merging things into master and not the gh-pages branch now?

**Comment by markwilliamfirth** [comment]
@iteles we are now 👍

**Comment by iteles** [comment]
In that case, was there a reason to merge this into GH-pages and not close it and open a quick PR directly to master as suggested above?

**Comment by markwilliamfirth** [comment]
The merge conflicts weren't difficult, it was just deleting the redesign folder

We are only now merging to master as I only just merged the gh branch to master

**Pull request merged**
