### PR TITLE
[PR] Fix CI and adding `Plausible` script

### LINKED ISSUE #505: GitHub Actions CI Failing
CI hasn't passed for a `while` ...  [GitHub Workflow Status](https://github.com/dwyl/dwyl-site/actions)
https://github.com/dwyl/dwyl-site/actions/workflows/ci.yml
image

It's using: https://github.com/Cyb3r-Jak3/html5validator-action
https://github.com/dwyl/dwyl-site/blob/9b35b2d05bc885634a16b9a7e7786913d678795a/.github/workflows/ci.yml#L15

# Todo

+ [ ] Get this working again.

### LINKED ISSUE #506: Replace Plausible Analytics with analytics.dwyl.com
Thanks to @LuchoTurtle our new `Analytics` instance is deployed! https://github.com/dwyl/learn-analytics/issues/3 🎉 

# Todo

+ [ ] Test the instance using the dwyl.com site

Snipet:
```html
<script defer data-domain="dwyl.com" src="https://analytics.dwyl.com/js/script.js"></script>
```

Thanks! 🙏

### PR DESCRIPTION
**Pull request by LuchoTurtle**
closes #505 
closes #506 

Fixes warnings.

### CODE REVIEW

**Comment by LuchoTurtle** [comment]
`Cyb3r-Jak3/html5validator-action@v7.2.0` keeps failing. :/ is this even needed?

**Comment by LuchoTurtle** [comment]
@nelsonic https://github.com/dwyl/dwyl-site/actions/runs/10389902639/job/28769062607?pr=507

Plenty of errors that the Validator finds. Am I meant to fix these?

**Comment by LuchoTurtle** [comment]
Went ahead and fixed all the warnings.

**Review by nelsonic — APPROVED** [review]
Thanks for fixing the HTML and updating the Analytics URL. 👌

**Comment by nelsonic** [comment]
Offline? https://github.com/dwyl/dwyl-site/issues/508 🤷‍♂️

**Pull request merged**
