### PR TITLE
Responsive site overhaul

### PR DESCRIPTION
**Pull request by finnhodgkin**
Adds responsive fixes to almost every page on the site. 

Also fixes a few missing favicon links and other small tweaks.

#362 #365

### CODE REVIEW

**Comment by markwilliamfirth** [comment]
@finnhodgkin this looks SO much better! Thank you!

I noticed there is still a slight issue with the nav bar (albeit the screen size the issue occurs at is probably not a common one)

screen shot 2017-09-25 at 17 06 08

**Comment by finnhodgkin** [comment]
@markwilliamfirth I was trying to stick to native tachyons as much as possible, but I think to fix that nav problem I'll have to add some custom styles - the breakpoints just don't work with the current padding.

**Comment by finnhodgkin** [comment]
With a bit of custom css that's fixed :+1:

**Comment by markwilliamfirth** [comment]
@finnhodgkin again, an odd size, but the SMG image doesn't look like it plays along and the navbar covers the top text slightly

screen shot 2017-09-25 at 18 15 47

**Comment by finnhodgkin** [comment]
Fixed :+1:

**Comment by finnhodgkin** [comment]
The MVP section still isn't looking great at medium scale. I'll try to fix it tomorrow. Think I'll have to add some custom css again :cry:.

**Comment by markwilliamfirth** [comment]
Gonna merge this one and then we can continue to improve on it 👍

**Pull request merged**
