### PR TITLE
Emf logo

### PR DESCRIPTION
**Pull request by rub1e**
Replaces off-white logo with white logo - answers #331

### CODE REVIEW

**Comment by rub1e** [comment]
On it

**Comment by rub1e** [comment]
Logo cropped to remove the whitespace so the height of the boxes isn't affected

**Comment by iteles** [comment]
Following the deletion of the `travis.yml` file as per #408, Travis now fails
screen shot 2018-05-23 at 11 27 13

No issues with this PR, so merging it in. I've also removed Travis as per #408.

**Comment by nelsonic** [comment]
@iteles we need to define a "workflow" for optimising "customer" logos for display on our website.
do you know if there is an issue open for this? (_I cannot find one..._)

**Pull request merged**
