### PR TITLE
Added José Cage to members list

### PR DESCRIPTION
**Pull request by JoseCage**
Thanks all. Especially @nelsonic 

I have added myself to members list. So i hope i have done in the right way.

:angola: :heart: **OpenSource**

### CODE REVIEW

**Comment by nelsonic** [comment]
@JoseCage 😍 
We need to _standardise_ our profile photos ... https://github.com/dwyl/hq/issues/150 📷 
But as a first PR this is _good_! 👍

**Comment by JoseCage** [comment]
Thanks @nelsonic 

I Will upload a new photo following the recommendations..

**Comment by JoseCage** [comment]
Just one more question.

What are the procedures for joining the team? (Such a proposal that you made me on **LinkedIn**).

Besides I have to learn more Javascript (seems to be the most used in dwyl) because I currently work more with PHP (But every challenge for me has its value).


**PS**: My english is still weak So forgive the mistakes. Lol :laughing:

**Comment by nelsonic** [comment]
@JoseCage "_weak_" English is an _opportunity_! It means you can read our "Book" from the perspective of a person whose  is `not ( first_language == "English" )` 
so you can ask questions (_by raising issues_) when we do not make something 100% clear!
Using PHP is _good_ because it means you have _some good_ Programming experience and can help us "_test_" our "Book" content... which is `!PHP` ... from the perspective of someone who "_speaks_" (_writes_) one of the _most_ popular languages but has _limited_ (_or zero_) XP with the languages _we_ are using... have you seen/tried: https://github.com/dwyl/learn-elm ? 😉

**Comment by JoseCage** [comment]
@nelsonic Honestly had seen the repo. But I have not tried Elm yet. Do you recommend adding it to my stacks (learn it)?

**Comment by nelsonic** [comment]
In case anyone `else` is following along, the "proposal" on LinkedIn is:
jose-cage-linkedin-proposal

In 2017 we're going to need to (_finally_) ***focus*** our efforts on building a "**Remote-_First_ Working Culture**" https://github.com/dwyl/remote-working
We'll need people to help "_guinea pig_" the process who we have _not_ worked with in ["**RL**"](https://en.wikipedia.org/wiki/Real_life)

**Comment by nelsonic** [comment]
@JoseCage _yes_ I'm _very_ ["_bullish_"](http://www.investopedia.com/study-guide/series-4/introduction/bullish-vs-bearish) on Elm for 2017. 👍 
If you have "_spare_" time to learn new things, push Elm to the _Top_ of your list! 😉

**Comment by JoseCage** [comment]
Thanks. Sure  will @nelsonic 


:portugal:  **PT**: Obrigado pela recomendação.

**Comment by markwilliamfirth** [comment]
With the new redesign of the site, the official members list has moved to GitHub and this legacy members list is currently members of the paid London team, this is subject to review and change in future depending on user testing, so for now this PR will be closed until this changes

**Comment by JoseCage** [comment]
No problem..

Thanks @markwilliamfirth

**Pull request closed without merging**
