### PR TITLE
Small updates to Services

### PR DESCRIPTION
**Pull request by markwilliamfirth**
https://github.com/dwyl/print-me/issues/25#issuecomment-307750296

### CODE REVIEW

**Comment by iteles** [comment]
https://github.com/dwyl/contributing#step-3-prepare-a-pull-request-pr-and-assign-to-someone-else-for-review

screen shot 2017-06-13 at 11 17 54

**Comment by markwilliamfirth** [comment]
@iteles not sure why this happened - I only made tiny text edits? How do we resolve this?

**Comment by SimonLab** [comment]
let's try to find out what's wrong :+1:

**Comment by markwilliamfirth** [comment]
@SimonLab I'm closing this PR, pulling down the code again and doing the changes again. I think it's because there has been changes in master compared to my local

**Pull request closed without merging**
