### PR TITLE
Updates Case Studies #304

### PR DESCRIPTION
**Pull request by markwilliamfirth**
Updates Case Studies.

In light of https://github.com/dwyl/dwyl-site/issues/304 I have added drafts of Pearson and OA (as per https://docs.google.com/spreadsheets/d/14fFQDGqhmucMQfkshR_8zdeZuZlhn8Rf1mFyXhi4Yi8/edit#gid=0 - linked issue is https://github.com/dwyl/hq/issues/377) to get the ball rolling now with regards to their approvals and also added good thinking logo (waiting on case study info)
This PR also updates company logos so they are all the same size now - these logos will require approval as part of case study approval

@finnhodgkin @ZooeyMiller please could you review this PR in terms of the code to make sure it doesn’t break anything? Inês will complete a separate review with regards to the content of these case studies at a later date once the content doc has been updated and the respective pages updated in a new PR

### CODE REVIEW

**Comment by markwilliamfirth** [comment]
Finn and Zooey are actually not on projects at the moment - @Cleop when you're back from hols can you help with checking and merging this one in plz?

**Comment by rub1e** [comment]
@Cleop presumably this can be closed once the branch I've just updated has been merged?

**Comment by markwilliamfirth** [comment]
Closing as I no longer work at dwyl - please use a new PR to carry any of these proposed changes forward

**Comment by iteles** [comment]
@rub1e 👍 Happy for these changes to be discarded as they are not relevant.

**Pull request closed without merging**
